### ISSUE TITLE
Exception with 2024.1 eap

### ISSUE THREAD

**Issue by jansorg** [casid/jte-intellij#45]
I'm not sure if that would also happen with non-eap builds, but this is shown in 2024.1 eap4:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jusecase.jte.intellij.language.convert.JteConvertFromJspAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jusecase.jte-intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)
```

**Comment by sschuberth** [comment]
Also happens with non-EAP version 2024.2.0.1.

**Comment by sschuberth** [comment]
https://github.com/casid/jte-intellij/issues/51 duplicates this, but as the description of the former is more telling, I propose to close this issue instead, even if it's older.
