### ISSUE TITLE
NullPointerException - JteUseScopeEnlarger.getAdditionalUseScope(JteUseScopeEnlarger.java:18)

### ISSUE THREAD

**Issue by jankod** [casid/jte-intellij#9]
java.lang.NullPointerException
	at org.jusecase.jte.intellij.language.refactoring.JteUseScopeEnlarger.getAdditionalUseScope(JteUseScopeEnlarger.java:18)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:79)
	at com.intellij.refactoring.rename.RenameUtil.processUsages(RenameUtil.java:106)
	at com.intellij.refactoring.rename.RenameUtil.findUsages(RenameUtil.java:75)
	at com.intellij.refactoring.rename.RenameUtil.findUsages(RenameUtil.java:61)
	at com.intellij.refactoring.rename.naming.AutomaticRenamer.findUsagesForElement(AutomaticRenamer.java:77)
	at com.intellij.refactoring.rename.naming.AutomaticRenamer.findUsages(AutomaticRenamer.java:53)
	at com.intellij.refactoring.rename.RenameProcessor.lambda$findRenamedVariables$2(RenameProcessor.java:250)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at com.intellij.refactoring.rename.RenameProcessor.lambda$findRenamedVariables$3(RenameProcessor.java:248)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:304)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:520)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by casid** [comment]
Thanks for reporting @jankod. This is fixed with 1.3.1. I just published the release, it's pending JetBrains approval now.

**Comment by casid** [comment]
1.3.1 plugin is approved and contains this fix.
